# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vDCRtGZ5-8Xnw_Asj1jsboUHvU0-oWD
"""

# ====================================================================
# All Necessary Imports
# ====================================================================
import streamlit as st
from streamlit_option_menu import option_menu
import pandas as pd
import numpy as np
import plotly.express as px
import shap
import matplotlib.pyplot as plt
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import warnings
from time import sleep
from scipy.sparse import issparse

# ====================================================================
# Visualization Functions
# ====================================================================
def custome_layout(fig, title_size=28, hover_font_size=18, showlegend=False):
    fig.update_layout(
        showlegend=showlegend,
        title={"font": {"size": title_size, "family": "tahoma"}},
        hoverlabel={"bgcolor": "#000", "font_size": hover_font_size, "font_family": "arial"}
    )

def box_plot(the_df, column):
    fig = px.box(
        data_frame=the_df, x=column, title=f'{column.title().replace("_", " ")} Distribution & 5-Summary',
        template="plotly_dark", labels={column: column.title().replace("_", " ")}, height=600,
        color_discrete_sequence=['#17B794']
    )
    custome_layout(fig, showlegend=False)
    return fig

def bar_plot(the_df, column, orientation="v", top_10=False):
    dep = the_df[column].value_counts()
    if top_10:
        dep = the_df[column].value_counts().nlargest(10)

    fig = px.bar(data_frame=dep,
                 x=dep.index,
                 y=dep.values,
                 orientation=orientation,
                 color=dep.index.astype(str),
                 title=f'Observations Distribution Via {column.title().replace("_", " ")}',
                 color_discrete_sequence=["#17B794"],
                 labels={"x": column.title().replace("_", " "),
                         "y": "Count of Employees"},
                 template="plotly_dark",
                 text_auto=True,
                 height=650)
    custome_layout(fig, title_size=28)
    return fig

def pie_chart(the_df, column):
    counts = the_df[column].value_counts()
    fig = px.pie(data_frame=counts,
                 names=counts.index,
                 values=counts.values,
                 title=f'Popularity of {column.title().replace("_", " ")}',
                 color_discrete_sequence=["#17B794", "#EEB76B", "#9C3D54"],
                 template="plotly_dark",
                 height=650
                 )
    custome_layout(fig, showlegend=True, title_size=28)
    pulls = np.zeros(len(counts))
    if len(pulls) > 1:
        pulls[-1] = 0.1
    fig.update_traces(
        textfont={"size": 16, "family": "arial", "color": "#fff"},
        hovertemplate="Label:%{label}<br>Frequency: %{value:0.4s}<br>Percentage: %{percent}",
        marker=dict(line=dict(color='#000000', width=0.5)),
        pull=pulls,
    )
    return fig

def create_heat_map(the_df):
    numeric_df = the_df.select_dtypes(include=np.number)
    correlation = numeric_df.corr()
    fig = px.imshow(
        correlation,
        template="plotly_dark",
        text_auto="0.2f",
        aspect=1,
        color_continuous_scale="greens",
        title="Correlation Heatmap of Data",
        height=650,
    )
    return fig

def create_vizualization(the_df, viz_type="box", data_type="number"):
    figs = []
    num_columns = list(the_df.select_dtypes(include=data_type).columns)
    cols_index = []

    if viz_type == "box":
        for i in range(len(num_columns)):
            if the_df[num_columns[i]].nunique() > 10:
                figs.append(box_plot(the_df, num_columns[i]))
                cols_index.append(i)

    if viz_type == "bar":
        for i in range(len(num_columns)):
            if the_df[num_columns[i]].nunique() < 15:
                figs.append(bar_plot(the_df, num_columns[i]))
                cols_index.append(i)

    if viz_type == "pie":
        num_columns = list(the_df.columns)
        for i in range(len(num_columns)):
            if 1 < the_df[num_columns[i]].nunique() <= 4:
                figs.append(pie_chart(the_df, num_columns[i]))
                cols_index.append(i)

    if len(cols_index) > 0:
        tabs = st.tabs([str(num_columns[i]).title().replace("_", " ") for i in cols_index])
        for i in range(len(cols_index)):
            tabs[i].plotly_chart(figs[i], use_container_width=True)

# ====================================================================
# Main App Function
# ====================================================================
def main():
    st.set_page_config(
        page_title="Employee Retention AI", page_icon="🤖", layout="wide"
    )
    warnings.simplefilter(action='ignore', category=FutureWarning)

    @st.cache_data
    def load_data_and_train_model():
        df = pd.read_csv('HR_comma_sep.csv')
        df_original = df.copy()
        df_train = df.drop_duplicates().reset_index(drop=True)
        X = df_train.drop('left', axis=1)
        y = df_train['left']
        categorical_features = X.select_dtypes(include=['object']).columns
        numerical_features = X.select_dtypes(include=np.number).columns
        preprocessor = ColumnTransformer(
            transformers=[
                ('num', StandardScaler(), numerical_features),
                ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)])
        best_params = {'n_estimators': 1888, 'learning_rate': 0.019, 'num_leaves': 22, 'max_depth': 11, 'random_state': 42}
        final_pipeline = Pipeline(steps=[
            ('preprocessor', preprocessor),
            ('classifier', lgb.LGBMClassifier(**best_params))])
        final_pipeline.fit(X, y)
        return final_pipeline, df_original

    pipeline, df = load_data_and_train_model()

    # ====================================================================
    # ✅ FIXED: SHAP Explanation Function (no JSONDecodeError)
    # ====================================================================
    @st.cache_data
    def get_shap_explanations(_pipeline, _df):
        model = _pipeline.named_steps['classifier']
        preprocessor = _pipeline.named_steps['preprocessor']
        X = _df.drop('left', axis=1).drop_duplicates()
        X_processed = preprocessor.transform(X)

        # Handle sparse matrices
        if issparse(X_processed):
            X_processed = X_processed.toarray()

        clean_names = [name.split('__')[-1].replace('_', ' ').title() for name in preprocessor.get_feature_names_out()]
        X_processed_df = pd.DataFrame(X_processed, columns=clean_names)

        # Extract booster safely
        booster = None
        if hasattr(model, "booster_"):
            booster = model.booster_
        elif hasattr(model, "_Booster"):
            booster = model._Booster
        elif hasattr(model, "booster"):
            booster = model.booster
        else:
            booster = model

        explainer = shap.TreeExplainer(booster)
        shap_values = explainer.shap_values(X_processed_df)
        return shap_values, X_processed_df

    # ====================================================================
    # Retention Strategy Function
    # ====================================================================
    def get_retention_strategies(employee_data):
        strategies = []
        if isinstance(employee_data, pd.DataFrame): employee_data = employee_data.iloc[0]
        if employee_data['satisfaction_level'] <= 0.45: strategies.append("Conduct a one-on-one meeting to discuss job satisfaction and well-being.")
        if employee_data['number_project'] <= 2: strategies.append("Employee may be under-utilized. Discuss career aspirations and find new projects.")
        if employee_data['number_project'] >= 6: strategies.append("Employee is at high risk of burnout. Assess workload and prioritize projects.")
        if employee_data['time_spend_company'] >= 4 and employee_data['promotion_last_5years'] == 0: strategies.append("Develop a clear career path and discuss opportunities for growth.")
        if employee_data['last_evaluation'] >= 0.8 and employee_data['satisfaction_level'] < 0.6: strategies.append("This is a high-performer but may be unhappy. Acknowledge contributions with rewards.")
        if not strategies: strategies.append("No specific high-risk factors detected, but continue to monitor engagement.")
        return strategies

    # ====================================================================
    # UI Styling
    # ====================================================================
    st.markdown(
        """<style>
        .main { text-align: center; }
        .st-emotion-cache-16txtl3 h1 { font: bold 29px arial; text-align: center; margin-bottom: 15px; }
        div[data-testid=stSidebarContent] { background-color: #111; border-right: 4px solid #222; padding: 8px!important; }
        div[data-testid=stFormSubmitButton]> button{ width: 100%; background-color: #111; border: 2px solid #17B794; padding: 18px; border-radius: 30px; opacity: 0.8; }
        div[data-testid=stFormSubmitButton]  p{ font-weight: bold; font-size : 20px; }
        div[data-testid=stFormSubmitButton]> button:hover{ opacity: 1; border: 2px solid #17B794; color: #fff; }
        </style>""", unsafe_allow_html=True
    )

    side_bar_options_style = {
        "container": {"padding": "0!important", "background-color": 'transparent'},
        "icon": {"color": "white", "font-size": "16px"},
        "nav-link": {"color": "#fff", "font-size": "18px", "text-align": "left", "margin": "0px", "margin-bottom": "15px"},
        "nav-link-selected": {"background-color": "#17B794", "font-size": "15px"},
    }

    with st.sidebar:
        st.title(":green[AI Retention] Assistant")
        st.title(":green[Develop by]-Nisarg Rathod")
        page = option_menu(
            menu_title=None,
            options=['Home', 'Vizualizations', 'Prediction', 'Explain Predictions'],
            icons=['diagram-3-fill', 'bar-chart-line-fill', "graph-up-arrow", 'lightbulb-fill'],
            menu_icon="cast", default_index=0, styles=side_bar_options_style
        )

    # ====================================================================
    # Pages
    # ====================================================================
    if page == "Home":
        st.header('Employee Retention Classification 👨‍💼')
        st.dataframe(df.head(100), use_container_width=True)
        st.write("***"); st.subheader("Data Summary Overview 🧐"); st.table(df.describe().T)

    if page == "Vizualizations":
        st.header("Data Vizualizations 📉")
        st.subheader("Numerical Data Distributions")
        create_vizualization(df, viz_type="box", data_type="number")
        st.subheader("Categorical Data Distributions")
        create_vizualization(df, viz_type="bar", data_type="object")
        st.subheader("Low-Cardinality Feature Distributions")
        create_vizualization(df, viz_type="pie")
        st.subheader("Feature Correlation Heatmap")
        st.plotly_chart(create_heat_map(df), use_container_width=True)

    if page == "Prediction":
        st.header("🎯 Predict Attrition & Get Recommendations")
        with st.form("Predict_value_form"):
            satisfaction_map = {'Very Dissatisfied': 0.1, 'Dissatisfied': 0.3, 'Neutral': 0.5, 'Satisfied': 0.7, 'Very Satisfied': 0.9}
            evaluation_map = {'Needs Improvement': 0.4, 'Meets Expectations': 0.7, 'Exceeds Expectations': 0.9}
            c1, c2 = st.columns(2)
            with c1:
                satisfaction_text = st.select_slider('Satisfaction Level', options=satisfaction_map.keys())
                evaluation_text = st.select_slider('Last Evaluation Score', options=evaluation_map.keys())
                number_project = st.slider('Number of Projects', 2, 7, 4)
                average_montly_hours = st.slider('Avg. Monthly Hours', 90, 310, 200)
                time_spend_company = st.slider('Years at Company', 2, 10, 3)
            with c2:
                work_accident_text = st.selectbox('Work Accident', ('No', 'Yes'))
                promotion_text = st.selectbox('Promotion in Last 5 Years', ('No', 'Yes'))
                Department = st.selectbox('Department', df['Department'].unique())
                salary = st.selectbox('Salary', df['salary'].unique())
            predict_button = st.form_submit_button(label='Get Prediction & Advice')

        if predict_button:
            satisfaction_level = satisfaction_map[satisfaction_text]; last_evaluation = evaluation_map[evaluation_text]
            Work_accident = 1 if work_accident_text == 'Yes' else 0; promotion_last_5years = 1 if promotion_text == 'Yes' else 0
            input_data = {'satisfaction_level': satisfaction_level, 'last_evaluation': last_evaluation,
                          'number_project': number_project, 'average_montly_hours': average_montly_hours,
                          'time_spend_company': time_spend_company, 'Work_accident': Work_accident,
                          'promotion_last_5years': promotion_last_5years, 'Department': Department, 'salary': salary}
            input_df = pd.DataFrame([input_data])
            with st.spinner('Analyzing Employee Profile...'):
                sleep(1); prediction = pipeline.predict(input_df)[0]; prediction_probas = pipeline.predict_proba(input_df)[0]
                st.subheader('Prediction Result'); st.write("---")
                pred_col, stay_prob_col, leave_prob_col = st.columns(3)
                with pred_col:
                    if prediction == 0: st.subheader("Employee is Likely to"); st.subheader(":green[STAY]")
                    else: st.subheader("Employee is Likely to"); st.subheader(":red[LEAVE]")
                with stay_prob_col: st.subheader("Probability to Stay"); st.subheader(f"{prediction_probas[0]:.2%}")
                with leave_prob_col: st.subheader("Probability to Leave"); st.subheader(f"{prediction_probas[1]:.2%}")
                st.write("---")
                if prediction == 1:
                    st.subheader('💡 Recommended Retention Strategies:')
                    recommendations = get_retention_strategies(input_df)
                    for i, rec in enumerate(recommendations, 1): st.info(f'{i}. {rec}')

    if page == "Explain Predictions":
        st.header("💡 Explaining The Model's Behavior")
        st.write("This page reveals the key factors our AI model uses to predict employee attrition. It helps us understand the **'why'** behind its decisions, making our AI transparent and trustworthy.")
        st.write("---")
        with st.spinner("Analyzing model insights..."):
            shap_values, X_processed_df = get_shap_explanations(pipeline, df)
            st.subheader("What are the Biggest Factors Driving Attrition?")
            fig2, ax2 = plt.subplots(); shap.summary_plot(shap_values, X_processed_df, plot_type='bar', show=False)
            st.pyplot(fig2, bbox_inches='tight'); plt.close(fig2)
            st.write("---"); st.subheader("How Do These Factors Influence Attrition Risk?")
            with st.expander("How to Read This Chart"):
                st.markdown("""- **Each dot** is an employee in our dataset.\n- **Factors are ranked by importance** from top to bottom.\n- The **horizontal position** of a dot shows its impact on the prediction. Dots to the right **increase the risk of leaving**, while dots to the left **decrease the risk**.\n- The **color** of the dot shows the feature's value for that employee. **Red** means a high value, **blue** means a low value.""")
            fig1, ax1 = plt.subplots(); shap.summary_plot(shap_values, X_processed_df, show=False, plot_type='dot')
            st.pyplot(fig1, bbox_inches='tight'); plt.close(fig1)
            st.subheader("Key Insights from the Model:")
            st.success("**1. Satisfaction is Critical:** Low satisfaction (blue dots) is the strongest single predictor that pushes an employee's attrition risk higher.")
            st.warning("**2. Workload is a Double-Edged Sword:** Both very high and very low numbers of projects increase attrition risk.")
            st.info("**3. Tenure Matters:** Employees are more likely to leave around the 4-5 year mark without promotion.")

if __name__ == "__main__":
    main()